workflows:
  ios_unsigned:
    name: iOS unsigned build (manual ipa)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Package .ipa manually
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
