workflows:
  ios_unsigned:
    name: iOS unsigned IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build iOS (no code sign)
        script: |
          flutter clean
          flutter build ios --release --no-codesign
      - name: Package .ipa
        script: |
          rm -rf Payload Runner.ipa
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
    artifacts:
      - Runner.ipa
